export const AUTH_REGISTER_FAILED = "AUTH_REGISTER_FAILED";
export const AUTH_REGISTER_LOADING = "AUTH_REGISTER_LOADING";
export const AUTH_REGISTER_RESET = "AUTH_REGISTER_RESET";
export const AUTH_REGISTER_SUCCESS = "AUTH_REGISTER_SUCCESS";

export const EMAIL_CONFIRMATION_DONE = "EMAIL_CONFIMATION_DONE";
export const EMAIL_CONFIRMATION_FAILED = "EMAIL_CONFIMATION_FAILED";
export const EMAIL_CONFIRMATION_LOADING = "EMAIL_CONFIMATION_LOADING";
export const EMAIL_CONFIRMATION_SUCCESS = "EMAIL_CONFIMATION_SUCCESS";