export const AUTH_FAILED = "AUTH_FAILED";
export const AUTH_LOADING = "AUTH_LOADING";
export const AUTH_SUCCESS = "AUTH_SUCCESS";

export const AUTH_LOGIN_FAILED = "AUTH_LOGIN_FAILED";
export const AUTH_LOGIN_LOADING = "AUTH_LOGIN_LOADING";
export const AUTH_LOGIN_RESET = "AUTH_LOGIN_RESET";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";

export const AUTH_REGISTER_FAILED = "AUTH_REGISTER_FAILED";
export const AUTH_REGISTER_LOADING = "AUTH_REGISTER_LOADING";
export const AUTH_REGISTER_RESET = "AUTH_REGISTER_RESET";
export const AUTH_REGISTER_SUCCESS = "AUTH_REGISTER_SUCCESS";

export const EMAIL_CONFIRMATION_DONE = "EMAIL_CONFIMATION_DONE";
export const EMAIL_CONFIRMATION_FAILED = "EMAIL_CONFIMATION_FAILED";
export const EMAIL_CONFIRMATION_LOADING = "EMAIL_CONFIMATION_LOADING";
export const EMAIL_CONFIRMATION_SUCCESS = "EMAIL_CONFIMATION_SUCCESS";